### ISSUE TITLE
libvgm-player has memory leaks

### ISSUE THREAD

**Issue by jpcima** [ValleyBell/libvgm#16] opened 2019-04-02 16:29 UTC
Destroying the player instance leaves some memory unfreed: resampler buffer, devices.
When the players are reinstantiated many times, the leaks accumulate.

[LeakSanitizer.txt.gz](https://github.com/ValleyBell/libvgm/files/3034979/LeakSanitizer.txt.gz)

**Comment by ValleyBell** [comment] 2019-04-02 20:10
Hmm ... that might be caused by me not calling `Stop` and `UnloadFile` in the destructor. 

Meanwhile you can work around that by following the order:  
_construct_, `LoadFile`, `Start`, `Render`, `Stop`, `UnloadFile`, _destruct_
That's how it is intended to be used. player.cpp does it what way and I haven't seen any major leaks there.

**Comment by jpcima** [comment] 2019-04-02 20:27
>Hmm ... that might be caused by me not calling Stop and UnloadFile in the destructor.

Tried right now, and you're absolutely correct. The leaks have been eliminated after the calls `Stop` and `UnloadFile`.

**Comment by ValleyBell** [comment] 2019-06-26 19:12
should be fixed by 66892701841707a46603d8a7dbad79d7492f1733

**Closed by ValleyBell** 2019-06-26 19:12 UTC
