### ISSUE TITLE
Volume very low on Psycho Soldier

### ISSUE THREAD

**Issue by jprjr** [ValleyBell/libvgm#78] opened 2021-08-30 18:28 UTC
Hi there - when I generate audio for Psycho Soldier (using the vgm2wav tool), the volume is very low.

Using the vgm2wav from VGMPlay, the volume seems fine - I think there's a gain setting in the VGM file that's not being applied?

**Comment by ValleyBell** [comment] 2021-08-30 20:31
You're right - that's indeed the case.
VGMPlay uses the `PlayerA` class for playback. (yeah, I know, I was super creative with naming)
That class does stuff like handling loops, fade out and volume gain.

vgm2wav uses `VGMPlayer`/`S98Player`/`DROPlayer` directly - and so it misses a few things.
I didn't update vgm2wav when writing the player wrapper class, sorry.

**Comment by jprjr** [comment] 2021-08-31 12:43
Question, from reading the code (haven't tried changing vgm2wav to use `PlayerA` yet):

It looks like changing the volume is happening in the application layer, VGMPlay [calculates a volume gain here](https://github.com/ValleyBell/vgmplay-libvgm/blob/6480d3e5c15336d6ed2e292d8c71d42bd51cfbcb/mediainfo.cpp#L72), then [sets the master volume here](https://github.com/ValleyBell/vgmplay-libvgm/blob/6480d3e5c15336d6ed2e292d8c71d42bd51cfbcb/playctrl.cpp#L423)

So I'm unsure if just changing to use `PlayerA` would result in the volume being handled, there's also some steps for the application to take.

Should setting a default volume be instead moved into the library, so a library user doesn't have to be concerned about the VGM file's gain setting? As far as I can tell, I don't *think* the `PlayerA` class is handling that (but please correct me if I'm wrong!)

**Comment by ValleyBell** [comment] 2021-08-31 16:56
Ohhh, that is a very good catch!

The way it works right now:
- `PlayerA` supports loops, fading, volume control, but defaults to volume `1.0`
- The application that "registers" the formats also has to evaluate the header information and has to adjust the `PlayerA` volume accordingly.

I think I did it this way to avoid `PlayerA` having to know about the details of the `VGMPlayer` class. It only includes `PlayerBase`.
I'll see if I can add a variable to the `PlayerBase` that contains the volume information, which `PlayerA` can then use.

**Comment by ValleyBell** [comment] 2021-09-30 18:21
This should be fixed as of 5af16c2bb62a1b2fa5f2b79d55b6007158bc074d.

Can you please check whether or not this fixes the problem for you and close the issue if so?

**Comment by ValleyBell** [comment] 2022-04-24 19:14
just a small reminder that you wanted to verify that the issue is solved now

**Comment by jprjr** [comment] 2022-04-24 20:24
Oh yes! Sorry about that - this fixes the issue

**Closed** 2022-04-24 20:27 UTC
Labels: bug, help wanted
